version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./key.pem:/etc/nginx/key.pem
  app:
      build: app
      env_file: .env
      depends_on: 
        - mariadb
      volumes:
        - ./app:/var/www/app
  mariadb:
    image: mariadb
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$SQL_PASS